### ISSUE TITLE
Fingerprint Image

### ISSUE THREAD

**Issue by mhsattarian** [adafruit/Adafruit_CircuitPython_Fingerprint#15]
Hey, thanks for the project. I grabbed the finger image from the sensor, using @stitchesnburns work (in pull requests), and it looks misplaced.

can you explain why the finger seems to be repeated 3 times with different details?

**Comment by jepler** [comment]
Good morning and thanks for your question.

It appears that the data should be organized as 128x288 pixels, not 192x192 pixels.  When I do this here, I get what appears to be a clear image of a fingerprint.  

PS A better place to ask for help with Adafruit CircuitPython software is on their [CircuitPython forum](https://forums.adafruit.com/viewforum.php?f=60).  In general, github issue trackers are not a place for discussion forums.  If you have a concern that applies to a not yet merged pull request, you should comment on that pull request.
