### ISSUE TITLE
Cannot find print

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_Fingerprint#20]
Just started playing with the R503 fingerprint sensor on a grandcentral_m4_express.
It seems to enroll fingerprints OK  so it is communicating but it repeatedly fails when trying to find a match.
I'm just using the fingerprint_simpletest.py from the examples.
Any suggestions?

```Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-alpha.1-45-g37e77b21c on 2020-07-14; Adafruit Grand Central M4 Express with samd51p20
>>> import finger
----------------
Fingerprint templates: [1]
e) enroll print
f) find print
d) delete print
----------------
> e
Enter ID # from 1-127: 2
Place finger on sensor........................................................................................................................................Image taken
Templating...Templated
Remove finger
Place same finger again................................................................Image taken
Templating...Templated
Creating model...Created
Storing model #2...Stored
----------------
Fingerprint templates: [1, 2]
e) enroll print
f) find print
d) delete print
----------------
> f
Waiting for image...
Templating...
Searching...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "finger.py", line 185, in <module>
  File "finger.py", line 34, in get_fingerprint
  File "adafruit_fingerprint.py", line 279, in finger_fast_search
  File "adafruit_fingerprint.py", line 292, in _get_packet
RuntimeError: Failed to read data from sensor
>>> 

```

**Comment by ladyada** [comment]
i havent done the change that this needs for the sensor, it uses a different search algorithm function

**Comment by jerryneedell** [comment]
Ah -- not a problem -- no rush -- just playing -- I can take a deeper look  to see if I can figure out what is needed or wait until it's ready.
Thanks.

**Comment by ladyada** [comment]
you could add these two functions - that will let it work
https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/commit/8792d131ed000ea21cac8d11a470eb8854a18a73#diff-e78dfca008f39f2023f2fa83f263ccb6R135
https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library/commit/8792d131ed000ea21cac8d11a470eb8854a18a73#diff-e78dfca008f39f2023f2fa83f263ccb6R292

**Comment by jerryneedell** [comment]
Thanks I will give it a try.

**Comment by jerryneedell** [comment]
@ladyada That works! Thanks

**Comment by ladyada** [comment]
incredible, could you PR? it would be a blessing!

**Comment by jerryneedell** [comment]
sure  -- will that also work in the original sensor? It looks like it has the same command.
SO should I update the example to just j=use the new fingerseach?
 -- or should there be 2 different examples?

**Comment by ladyada** [comment]
ill test the PR but yeah its a tiny bit slower but works just the same

**Comment by jerryneedell** [comment]
OK -- just need to get pylint happy -- should have it in soon.

**Comment by ladyada** [comment]
thanks :)
