### ISSUE TITLE
remove print "flush" arguments  in examples -- not accepted by CirCuitPython

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_Fingerprint#32]
The examples use the argument "flush=True"  in many of the print statements but this is not recognized but CircuitPython and it throws an error.

**Comment by jerryneedell** [comment]
This appears to be A bug in CircuitPyhton and should be fixed there
https://github.com/adafruit/circuitpython/issues/4888
leaving open until it is

**Comment by tekktrik** [comment]
Looks like the decision was to remove the `flush` argument in the examples then!  Adding the "First Good Issue" label so it gets tagged for Hacktoberfest!
