### ISSUE TITLE
Hitting memory issues on M0 boards

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_Fingerprint#33]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=58&t=180064

Guide shows using with a Trinket M0:
https://learn.adafruit.com/adafruit-optical-fingerprint-sensor/circuitpython#circuitpython-microcontroller-wiring-3044423-6

But doing so runs into memory issue:
```python
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit Trinket M0 with samd21e18
>>> import fingerprint_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fingerprint_simpletest.py", line 8, in <module>
  File "adafruit_fingerprint.py", line 94, in <module>
MemoryError: memory allocation failed, allocating 296 bytes
>>> 
```

**Comment by ladyada** [comment]
ah could be - @kattni wanna update the guide to feather m4 or such? add a note that SAMD21 and other very-low-memory devices wont be able to run?

**Comment by kattni** [comment]
Guide updated, warnings added. @caternuson Feel free to reply to the forum thread if needed. Thanks!
