### ISSUE TITLE
import typing / import ustruct

### ISSUE THREAD

**Issue by FlamyEdge** [adafruit/Adafruit_CircuitPython_Fingerprint#36]
I'm using a Metro M0 express with Circuitpython 7.0.0 and when I try to run a simple code with `import adafruit_fingerprint` I get a `ImportError: no module named 'ustruct'`. While checking the code I saw that the fingerrprint lib try to import ustruct only if typing, busio or struct isn't present. By checking the default module of Circuitpython 7.0.0 I can confirm the absence of typing and ustruct.
Am I missing something?

**Comment by dhalbert** [comment]
Fixed by #40.
