### ISSUE TITLE
import  error

### ISSUE THREAD

**Issue by Gozzy97** [adafruit/Adafruit_CircuitPython_Fingerprint#43]
after running the fingerprint_simpletest.py code i received this error.
I'm running the code in my esp8266  board with the Micropython firmware.

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
ImportError: no module named 'board'

**Comment by ladyada** [comment]
you could try to use blinka
https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico
but the esp8266 is a very small board - it might be best to find a micropython-specific library

**Comment by Gozzy97** [comment]
Thank you so much ladyada for your prompt reply. I'm really grateful to you.


I will get to you soon when i must have tried out your suggestions.


Please can I get a pdf or a link to a comprehensive tutorial for circuit
python it would go a long way to helping me in this new career path i have
chosen.

Accept the assurances of my high regards.

Nnagozie.
