### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Gozzy97** [adafruit/Adafruit_CircuitPython_Fingerprint#44]
Thanks for helping me out with the Import Error I had yesterday i have come through it now with your steps.
But I had another error trying to to run the "fingerprint_simplest.py" example code. Below is the error I got while trying to run the code on my esp. 8266 micro controller device. I would be glad if you can reply as prompt as you had always done.

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/lib/board.py", line 39, in <module>
  File "/lib/adafruit_platformdetect/__init__.py", line 10, in <module>
MemoryError:

**Comment by ladyada** [comment]
yep you have run out of memory, if you need more help with micropython please post to micropython forums. this is where bug reports go.

**Comment by Gozzy97** [comment]
Okay.
Thank you so much for your usual prompt response.

I'll enquire more on micropython forum.

My regards.
