### ISSUE TITLE
How can I use Adafruit_CircuitPython_Fingerprint in Micropython to run on ESP32 wroom.

### ISSUE THREAD

**Issue by rkverma2022** [adafruit/Adafruit_CircuitPython_Fingerprint#54]
I have already written code using micropython for other feature using threading, socket, now i want to add fingerprint feature. How can I do that ? I don't want to disturb other features.

**Comment by FoamyGuy** [comment]
We have https://github.com/adafruit/Adafruit_Blinka that is a compatibility layer for micropython and a guide here: https://learn.adafruit.com/circuitpython-libraries-on-micropython-using-the-raspberry-pi-pico/installing-blinka-and-libraries that illustrates it's usage, though it's on an RP2040 and it doesn't deal with this library specifically. 

I don't believe there is any specific documentation around that setup. If you try it and have specific issues you can come join on discord to ask, though we support circuitpython direct most primarily.
